### ISSUE TITLE
[BUG] Datapack doesnt enable

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [eingruenesbeb/Villager-Bonk#3]
**Describe the bug**
[19:14:41] [Server thread/ERROR] (Minecraft) Failed to load function eingruenesbeb.bonk_villager:_run_trigger
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Failed to parse structure: Failed to get element ResourceKey[minecraft:item_modifier / eingruenesbeb.bonk_villager:convert_stick] at position 140: ...vert_stick<--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Failed to parse structure: Failed to get element ResourceKey[minecraft:item_modifier / eingruenesbeb.bonk_villager:convert_stick] at position 140: ...vert_stick<--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more

**To Reproduce**
1. Install datapack

**Expected behavior**
Datapack works

**Screenshots**

**Version:**
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
| Bonk Villager by @eingruenesbeb               |
| Version: 1.4 for MC1.21                               |
| Report Bugs or check out the code on Github.  |
| Get help or hang out on Discord.                  |
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

**Additional context**

**Comment by eingruenesbeb** [comment]
What Minecraft version are you on?
Using the latest datapack version, I was able to load it correctly. 
It may also be helpful to do a checksum check (sha256). It should be `3d511c463b1d35545441cdce356d3098b1b2a55febb1c18b8b4aeb6f02132b68`.
Here are the console commands to check it:
- On Linux: 
```sh
sha256sum "Bonk Villager v1.4.1-MC1.21.zip" | awk '$1==""{print"All good :)"} $1!="3d511c463b1d35545441cdce356d3098b1b2a55febb1c18b8b4aeb6f02132b68"{print"Something is off... :("}'
```
- On Windows:
```ps1
if ((Get-FileHash "Bonk Villager v1.4.1-MC1.21.zip" -Algorithm SHA256).Hash -eq "3d511c463b1d35545441cdce356d3098b1b2a55febb1c18b8b4aeb6f02132b68") {
    Write-Output "All good :)"
} else {
    Write-Output "Something is wrong... :("
}
```

**Comment by MrMasrozYTLIVE** [comment]
> What Minecraft version are you on? Using the latest datapack version, I was able to load it correctly. It may also be helpful to do a checksum check (sha256). It should be `3d511c463b1d35545441cdce356d3098b1b2a55febb1c18b8b4aeb6f02132b68`. Here are the console commands to check it:
> 
> * On Linux:
> 
> ```shell
> sha256sum "Bonk Villager v1.4.1-MC1.21.zip" | awk '$1==""{print"All good :)"} $1!="3d511c463b1d35545441cdce356d3098b1b2a55febb1c18b8b4aeb6f02132b68"{print"Something is off... :("}'
> ```
> 
> * On Windows:
> 
> ```powershell
> if ((Get-FileHash "Bonk Villager v1.4.1-MC1.21.zip" -Algorithm SHA256).Hash -eq "3d511c463b1d35545441cdce356d3098b1b2a55febb1c18b8b4aeb6f02132b68") {
>     Write-Output "All good :)"
> } else {
>     Write-Output "Something is wrong... :("
> }
> ```

I can't really verify hash of archive since its pterodactyl-based hosting. 

We are using 1.12.1 Fabric

**Comment by MrMasrozYTLIVE** [comment]
On my PC checking hash gave `All good :)`
UPD. Downloaded datapack from hosting and it also says `All good :)`

**Comment by eingruenesbeb** [comment]
> We are using 1.12.1 Fabric

There's the issue. This version is unfortunatly not supported. Now that I know, that users on that version exist, I might add support for it, but you'll have to find a replacement for it for now.

**Comment by eingruenesbeb** [comment]
Earliest supported version is 1.16.
